"""Constants for heat exchanger network grid diagrams."""

from __future__ import annotations

_DUTY_TOLERANCE_KW = 1.0
_DEFAULT_STREAM_LINE_WIDTH = 5.0
_LAYOUT_X_MIN = 0.0
_LAYOUT_X_MAX = 1.0
_MIN_FIGURE_WIDTH_PX = 960
_MIN_FIGURE_HEIGHT_PX = 260
_LANE_HEIGHT_PX = 46
_GROUP_GAP_LANES = 0.1
_MIN_MARKER_RADIUS = 35.0
_MAX_MARKER_RADIUS = 70.0
_MARKER_ROW_PITCH_RATIO = 0.8
_STREAM_LINE_TO_MARKER_RADIUS_RATIO = 0.1
_MATCH_LINE_TO_STREAM_LINE_WIDTH_RATIO = 0.5
_HOT_STREAM_COLOR = "#ff8f8f"
_COLD_STREAM_COLOR = "#9ec5fe"
_HOT_UTILITY_COLOR = "#b00020"
_COLD_UTILITY_COLOR = "#0b1f4d"
_RECOVERY_MATCH_COLOR = "#3f3f46"
_LABEL_BACKGROUND_COLOR = "rgba(255,255,255,0.82)"
