"""Typed configuration primitives and schemas for OpenPinch.

The :mod:`OpenPinch.lib` package exposes enumerations, configuration helpers,
and the Pydantic schema models that define the wire format used by the public
API.  They are re-exported here for consumers that need to construct or inspect
inputs programmatically."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from . import (
        config,
        enums,
        heat_exchanger_network_types,
        problem_table_types,
        schemas,
    )
    from .config import ACTIVATE_TIMING, LOG_TIMING, T_CRIT, C_to_K, Configuration, tol
    from .enums import (
        GT,
        HEN,
        PT,
        SD,
        SID,
        ST,
        TT,
        ZT,
        ArrowHead,
        BB_Minimiser,
        CogenerationTarget,
        FluidPhase,
        GraphType,
        HeatExchangerKind,
        HeatExchangerNetworkDesignMethod,
        HeatExchangerNetworkLabel,
        HeatExchangerStreamRole,
        HeatExchangerTypes,
        HeatFlowUnits,
        HeatPump,
        HeatPumpAndRefrigerationCycle,
        HENDesignMethod,
        HPRcycle,
        LegendSeries,
        LineColour,
        ProblemTableLabel,
        ResultsType,
        StreamDataLabel,
        StreamID,
        StreamLoc,
        StreamType,
        SummaryRowType,
        TargetType,
        TurbineModel,
        ZoneType,
    )
    from .heat_exchanger_network_types import HeatExchangerNetworkLabelKey
    from .problem_table_types import (
        ProblemTableColumnKey,
        ProblemTableColumnUpdates,
        ProblemTableUpdateKwargs,
    )
    from .schemas import (
        AnyTargetModel,
        BaseTargetModel,
        ConfigurationFieldMetadata,
        DataPoint,
        DirectHeatPumpTarget,
        DirectIntegrationTarget,
        DirectRefrigerationTarget,
        EnergyTransferTarget,
        Graph,
        GraphAvailability,
        GraphCatalogEntry,
        GraphDataEntry,
        GraphSet,
        HeatExchangerNetworkSynthesisExportRecord,
        HeatExchangerNetworkSynthesisManifest,
        HeatExchangerNetworkSynthesisMethodInput,
        HeatExchangerNetworkSynthesisMethodOutput,
        HeatExchangerNetworkSynthesisResult,
        HeatExchangerNetworkSynthesisTask,
        HeatExchangerNetworkSynthesisTaskOutcome,
        HeatExchangerNetworkTopologyRestriction,
        HeatPumpTargetBase,
        HeatPumpTargetInputs,
        HeatPumpTargetOutputs,
        HeatUtility,
        HPRBackendResult,
        HPRMetric,
        HPRParsedState,
        HPRThermoArtifacts,
        IndirectHeatPumpTarget,
        IndirectRefrigerationTarget,
        InputRecordView,
        MaybeVU,
        NonLinearStream,
        PeriodValueWithUnit,
        PinchTemp,
        PinchWorkspaceBundle,
        ProblemReport,
        ProblemTableDiffView,
        ProblemTableView,
        ReportMetric,
        ScalarOrVU,
        ScenarioComparisonView,
        ScenarioVariantBundleEntry,
        ScenarioVariantView,
        ScenarioWorkflowConfig,
        Segment,
        StreamSchema,
        SummaryCard,
        SynthesisDesignMethod,
        SynthesisMethod,
        SynthesisOutputFormat,
        SynthesisTaskStatus,
        TableView,
        TargetInput,
        TargetOutput,
        TargetResults,
        TotalProcessTarget,
        TotalSiteTarget,
        TurbineSolveResult,
        TurbineStageResult,
        UtilitySchema,
        UtilitySummaryTarget,
        ValidationIssue,
        ValidationReport,
        ValueWithUnit,
        VariantInputView,
        VariantMetricDelta,
        ZoneNodeView,
        ZoneTreeSchema,
    )

__all__ = [
    "config",
    "enums",
    "heat_exchanger_network_types",
    "problem_table_types",
    "schemas",
    "ACTIVATE_TIMING",
    "C_to_K",
    "CogenerationTarget",
    "Configuration",
    "LOG_TIMING",
    "T_CRIT",
    "tol",
    "ArrowHead",
    "BB_Minimiser",
    "GraphType",
    "FluidPhase",
    "GT",
    "HENDesignMethod",
    "HeatExchangerKind",
    "HeatExchangerNetworkDesignMethod",
    "HeatExchangerNetworkLabel",
    "HeatExchangerStreamRole",
    "HEN",
    "HeatExchangerTypes",
    "HeatFlowUnits",
    "HeatPump",
    "HeatPumpAndRefrigerationCycle",
    "HPRcycle",
    "LegendSeries",
    "LineColour",
    "ProblemTableLabel",
    "PT",
    "ResultsType",
    "SID",
    "SD",
    "ST",
    "StreamDataLabel",
    "StreamID",
    "StreamLoc",
    "StreamType",
    "SummaryRowType",
    "TargetType",
    "TT",
    "TurbineModel",
    "ZoneType",
    "ZT",
    "HeatExchangerNetworkLabelKey",
    "ProblemTableColumnKey",
    "ProblemTableColumnUpdates",
    "ProblemTableUpdateKwargs",
    "HPRMetric",
    "MaybeVU",
    "ScalarOrVU",
    "PeriodValueWithUnit",
    "ValueWithUnit",
    "DataPoint",
    "Graph",
    "GraphAvailability",
    "GraphSet",
    "Segment",
    "HeatPumpTargetInputs",
    "HeatPumpTargetOutputs",
    "HeatExchangerNetworkSynthesisExportRecord",
    "HeatExchangerNetworkSynthesisManifest",
    "HeatExchangerNetworkSynthesisMethodInput",
    "HeatExchangerNetworkSynthesisMethodOutput",
    "HeatExchangerNetworkSynthesisResult",
    "HeatExchangerNetworkSynthesisTask",
    "HeatExchangerNetworkSynthesisTaskOutcome",
    "HeatExchangerNetworkTopologyRestriction",
    "SynthesisDesignMethod",
    "SynthesisMethod",
    "SynthesisOutputFormat",
    "SynthesisTaskStatus",
    "HPRParsedState",
    "HPRThermoArtifacts",
    "HPRBackendResult",
    "NonLinearStream",
    "StreamSchema",
    "TargetInput",
    "TargetOutput",
    "UtilitySchema",
    "ZoneTreeSchema",
    "HeatUtility",
    "TargetResults",
    "PinchTemp",
    "ProblemReport",
    "AnyTargetModel",
    "BaseTargetModel",
    "DirectHeatPumpTarget",
    "DirectIntegrationTarget",
    "DirectRefrigerationTarget",
    "EnergyTransferTarget",
    "HeatPumpTargetBase",
    "IndirectHeatPumpTarget",
    "IndirectRefrigerationTarget",
    "TotalProcessTarget",
    "TotalSiteTarget",
    "UtilitySummaryTarget",
    "TurbineSolveResult",
    "TurbineStageResult",
    "ConfigurationFieldMetadata",
    "GraphCatalogEntry",
    "GraphDataEntry",
    "InputRecordView",
    "ProblemTableDiffView",
    "ProblemTableView",
    "ScenarioComparisonView",
    "ScenarioVariantBundleEntry",
    "ScenarioVariantView",
    "ScenarioWorkflowConfig",
    "PinchWorkspaceBundle",
    "ReportMetric",
    "SummaryCard",
    "TableView",
    "ValidationIssue",
    "ValidationReport",
    "VariantMetricDelta",
    "VariantInputView",
    "ZoneNodeView",
]

_EXPORTS: dict[str, tuple[str, str | None]] = {
    "config": ("OpenPinch.lib.config", None),
    "enums": ("OpenPinch.lib.enums", None),
    "heat_exchanger_network_types": (
        "OpenPinch.lib.heat_exchanger_network_types",
        None,
    ),
    "problem_table_types": ("OpenPinch.lib.problem_table_types", None),
    "schemas": ("OpenPinch.lib.schemas", None),
    "ACTIVATE_TIMING": ("OpenPinch.lib.config", "ACTIVATE_TIMING"),
    "LOG_TIMING": ("OpenPinch.lib.config", "LOG_TIMING"),
    "T_CRIT": ("OpenPinch.lib.config", "T_CRIT"),
    "C_to_K": ("OpenPinch.lib.config", "C_to_K"),
    "Configuration": ("OpenPinch.lib.config", "Configuration"),
    "tol": ("OpenPinch.lib.config", "tol"),
    "GT": ("OpenPinch.lib.enums", "GT"),
    "HEN": ("OpenPinch.lib.enums", "HEN"),
    "PT": ("OpenPinch.lib.enums", "PT"),
    "SD": ("OpenPinch.lib.enums", "SD"),
    "SID": ("OpenPinch.lib.enums", "SID"),
    "ST": ("OpenPinch.lib.enums", "ST"),
    "TT": ("OpenPinch.lib.enums", "TT"),
    "ZT": ("OpenPinch.lib.enums", "ZT"),
    "ArrowHead": ("OpenPinch.lib.enums", "ArrowHead"),
    "BB_Minimiser": ("OpenPinch.lib.enums", "BB_Minimiser"),
    "CogenerationTarget": ("OpenPinch.lib.enums", "CogenerationTarget"),
    "FluidPhase": ("OpenPinch.lib.enums", "FluidPhase"),
    "GraphType": ("OpenPinch.lib.enums", "GraphType"),
    "HeatExchangerKind": ("OpenPinch.lib.enums", "HeatExchangerKind"),
    "HeatExchangerNetworkDesignMethod": (
        "OpenPinch.lib.enums",
        "HeatExchangerNetworkDesignMethod",
    ),
    "HeatExchangerNetworkLabel": ("OpenPinch.lib.enums", "HeatExchangerNetworkLabel"),
    "HeatExchangerStreamRole": ("OpenPinch.lib.enums", "HeatExchangerStreamRole"),
    "HeatExchangerTypes": ("OpenPinch.lib.enums", "HeatExchangerTypes"),
    "HeatFlowUnits": ("OpenPinch.lib.enums", "HeatFlowUnits"),
    "HeatPump": ("OpenPinch.lib.enums", "HeatPump"),
    "HeatPumpAndRefrigerationCycle": (
        "OpenPinch.lib.enums",
        "HeatPumpAndRefrigerationCycle",
    ),
    "HENDesignMethod": ("OpenPinch.lib.enums", "HENDesignMethod"),
    "HPRcycle": ("OpenPinch.lib.enums", "HPRcycle"),
    "LegendSeries": ("OpenPinch.lib.enums", "LegendSeries"),
    "LineColour": ("OpenPinch.lib.enums", "LineColour"),
    "ProblemTableLabel": ("OpenPinch.lib.enums", "ProblemTableLabel"),
    "ResultsType": ("OpenPinch.lib.enums", "ResultsType"),
    "StreamDataLabel": ("OpenPinch.lib.enums", "StreamDataLabel"),
    "StreamID": ("OpenPinch.lib.enums", "StreamID"),
    "StreamLoc": ("OpenPinch.lib.enums", "StreamLoc"),
    "StreamType": ("OpenPinch.lib.enums", "StreamType"),
    "SummaryRowType": ("OpenPinch.lib.enums", "SummaryRowType"),
    "TargetType": ("OpenPinch.lib.enums", "TargetType"),
    "TurbineModel": ("OpenPinch.lib.enums", "TurbineModel"),
    "ZoneType": ("OpenPinch.lib.enums", "ZoneType"),
    "HeatExchangerNetworkLabelKey": (
        "OpenPinch.lib.heat_exchanger_network_types",
        "HeatExchangerNetworkLabelKey",
    ),
    "ProblemTableColumnKey": (
        "OpenPinch.lib.problem_table_types",
        "ProblemTableColumnKey",
    ),
    "ProblemTableColumnUpdates": (
        "OpenPinch.lib.problem_table_types",
        "ProblemTableColumnUpdates",
    ),
    "ProblemTableUpdateKwargs": (
        "OpenPinch.lib.problem_table_types",
        "ProblemTableUpdateKwargs",
    ),
    "AnyTargetModel": ("OpenPinch.lib.schemas", "AnyTargetModel"),
    "BaseTargetModel": ("OpenPinch.lib.schemas", "BaseTargetModel"),
    "ConfigurationFieldMetadata": (
        "OpenPinch.lib.schemas",
        "ConfigurationFieldMetadata",
    ),
    "DataPoint": ("OpenPinch.lib.schemas", "DataPoint"),
    "DirectHeatPumpTarget": ("OpenPinch.lib.schemas", "DirectHeatPumpTarget"),
    "DirectIntegrationTarget": ("OpenPinch.lib.schemas", "DirectIntegrationTarget"),
    "DirectRefrigerationTarget": ("OpenPinch.lib.schemas", "DirectRefrigerationTarget"),
    "EnergyTransferTarget": ("OpenPinch.lib.schemas", "EnergyTransferTarget"),
    "Graph": ("OpenPinch.lib.schemas", "Graph"),
    "GraphAvailability": ("OpenPinch.lib.schemas", "GraphAvailability"),
    "GraphCatalogEntry": ("OpenPinch.lib.schemas", "GraphCatalogEntry"),
    "GraphDataEntry": ("OpenPinch.lib.schemas", "GraphDataEntry"),
    "GraphSet": ("OpenPinch.lib.schemas", "GraphSet"),
    "HeatExchangerNetworkSynthesisExportRecord": (
        "OpenPinch.lib.schemas.synthesis.common",
        "HeatExchangerNetworkSynthesisExportRecord",
    ),
    "HeatExchangerNetworkSynthesisManifest": (
        "OpenPinch.lib.schemas.synthesis.common",
        "HeatExchangerNetworkSynthesisManifest",
    ),
    "HeatExchangerNetworkSynthesisMethodInput": (
        "OpenPinch.lib.schemas.synthesis.method",
        "HeatExchangerNetworkSynthesisMethodInput",
    ),
    "HeatExchangerNetworkSynthesisMethodOutput": (
        "OpenPinch.lib.schemas.synthesis.method",
        "HeatExchangerNetworkSynthesisMethodOutput",
    ),
    "HeatExchangerNetworkSynthesisResult": (
        "OpenPinch.lib.schemas.synthesis.result",
        "HeatExchangerNetworkSynthesisResult",
    ),
    "HeatExchangerNetworkSynthesisTask": (
        "OpenPinch.lib.schemas.synthesis.task",
        "HeatExchangerNetworkSynthesisTask",
    ),
    "HeatExchangerNetworkSynthesisTaskOutcome": (
        "OpenPinch.lib.schemas.synthesis.task",
        "HeatExchangerNetworkSynthesisTaskOutcome",
    ),
    "HeatExchangerNetworkTopologyRestriction": (
        "OpenPinch.lib.schemas.synthesis.topology",
        "HeatExchangerNetworkTopologyRestriction",
    ),
    "HeatPumpTargetBase": ("OpenPinch.lib.schemas", "HeatPumpTargetBase"),
    "HeatPumpTargetInputs": ("OpenPinch.lib.schemas", "HeatPumpTargetInputs"),
    "HeatPumpTargetOutputs": ("OpenPinch.lib.schemas", "HeatPumpTargetOutputs"),
    "HeatUtility": ("OpenPinch.lib.schemas", "HeatUtility"),
    "HPRBackendResult": ("OpenPinch.lib.schemas", "HPRBackendResult"),
    "HPRMetric": ("OpenPinch.lib.schemas", "HPRMetric"),
    "HPRParsedState": ("OpenPinch.lib.schemas", "HPRParsedState"),
    "HPRThermoArtifacts": ("OpenPinch.lib.schemas", "HPRThermoArtifacts"),
    "IndirectHeatPumpTarget": ("OpenPinch.lib.schemas", "IndirectHeatPumpTarget"),
    "IndirectRefrigerationTarget": (
        "OpenPinch.lib.schemas",
        "IndirectRefrigerationTarget",
    ),
    "InputRecordView": ("OpenPinch.lib.schemas", "InputRecordView"),
    "MaybeVU": ("OpenPinch.lib.schemas", "MaybeVU"),
    "NonLinearStream": ("OpenPinch.lib.schemas", "NonLinearStream"),
    "PeriodValueWithUnit": ("OpenPinch.lib.schemas", "PeriodValueWithUnit"),
    "PinchTemp": ("OpenPinch.lib.schemas", "PinchTemp"),
    "PinchWorkspaceBundle": ("OpenPinch.lib.schemas", "PinchWorkspaceBundle"),
    "ProblemReport": ("OpenPinch.lib.schemas", "ProblemReport"),
    "ProblemTableDiffView": ("OpenPinch.lib.schemas", "ProblemTableDiffView"),
    "ProblemTableView": ("OpenPinch.lib.schemas", "ProblemTableView"),
    "ReportMetric": ("OpenPinch.lib.schemas", "ReportMetric"),
    "ScalarOrVU": ("OpenPinch.lib.schemas", "ScalarOrVU"),
    "ScenarioComparisonView": ("OpenPinch.lib.schemas", "ScenarioComparisonView"),
    "ScenarioVariantBundleEntry": (
        "OpenPinch.lib.schemas",
        "ScenarioVariantBundleEntry",
    ),
    "ScenarioVariantView": ("OpenPinch.lib.schemas", "ScenarioVariantView"),
    "ScenarioWorkflowConfig": ("OpenPinch.lib.schemas", "ScenarioWorkflowConfig"),
    "Segment": ("OpenPinch.lib.schemas", "Segment"),
    "StreamSchema": ("OpenPinch.lib.schemas", "StreamSchema"),
    "SummaryCard": ("OpenPinch.lib.schemas", "SummaryCard"),
    "SynthesisDesignMethod": (
        "OpenPinch.lib.schemas.synthesis.common",
        "SynthesisDesignMethod",
    ),
    "SynthesisMethod": ("OpenPinch.lib.schemas.synthesis.common", "SynthesisMethod"),
    "SynthesisOutputFormat": (
        "OpenPinch.lib.schemas.synthesis.common",
        "SynthesisOutputFormat",
    ),
    "SynthesisTaskStatus": (
        "OpenPinch.lib.schemas.synthesis.common",
        "SynthesisTaskStatus",
    ),
    "TableView": ("OpenPinch.lib.schemas", "TableView"),
    "TargetInput": ("OpenPinch.lib.schemas", "TargetInput"),
    "TargetOutput": ("OpenPinch.lib.schemas", "TargetOutput"),
    "TargetResults": ("OpenPinch.lib.schemas", "TargetResults"),
    "TotalProcessTarget": ("OpenPinch.lib.schemas", "TotalProcessTarget"),
    "TotalSiteTarget": ("OpenPinch.lib.schemas", "TotalSiteTarget"),
    "TurbineSolveResult": ("OpenPinch.lib.schemas", "TurbineSolveResult"),
    "TurbineStageResult": ("OpenPinch.lib.schemas", "TurbineStageResult"),
    "UtilitySchema": ("OpenPinch.lib.schemas", "UtilitySchema"),
    "UtilitySummaryTarget": ("OpenPinch.lib.schemas", "UtilitySummaryTarget"),
    "ValidationIssue": ("OpenPinch.lib.schemas", "ValidationIssue"),
    "ValidationReport": ("OpenPinch.lib.schemas", "ValidationReport"),
    "ValueWithUnit": ("OpenPinch.lib.schemas", "ValueWithUnit"),
    "VariantInputView": ("OpenPinch.lib.schemas", "VariantInputView"),
    "VariantMetricDelta": ("OpenPinch.lib.schemas", "VariantMetricDelta"),
    "ZoneNodeView": ("OpenPinch.lib.schemas", "ZoneNodeView"),
    "ZoneTreeSchema": ("OpenPinch.lib.schemas", "ZoneTreeSchema"),
}


def __getattr__(name: str) -> Any:
    try:
        module_name, attribute = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    module = import_module(module_name)
    value = module if attribute is None else getattr(module, attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__) | set(_EXPORTS))
