name: CI Main
on:
  push:
    branches: ["main"]
permissions:
  contents: read
concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validation:
    uses: ./.github/workflows/ci-validation.yml
    with:
      candidate: ${{ github.sha }}
      profile: full
